#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# wallpaper
swww-daemon &
if [ -f ~/.cache/current_wallpaper ]; then
    $scripts/wall "$(cat ~/.cache/current_wallpaper)" &
else
    $scripts/wall /home/rodrigo/Documents/Wallpapers/ColorWall-gpgyw3.jpg &
fi

# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=secrets &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GITHUB_TOKEN GITHUB_USERNAME &

wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

qs -c overview &
qs -c powermenu &
qs -c dashboard &
qs -c search &
qs -c wallpaper &
qs -c notifications &
qs -c network &
qs -c waybar &
qs -c bluetooth &
qs -c audio &
qs -c overview &
qs -c search_clipboard &
qs -c github_dashboard &
